//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArielProject.TaxiServiceAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaxiServiceAPI.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name customerName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookRide", ReplyAction="*")]
        ArielProject.TaxiServiceAPI.BookRideResponse BookRide(ArielProject.TaxiServiceAPI.BookRideRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookRide", ReplyAction="*")]
        System.Threading.Tasks.Task<ArielProject.TaxiServiceAPI.BookRideResponse> BookRideAsync(ArielProject.TaxiServiceAPI.BookRideRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookRideRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookRide", Namespace="http://tempuri.org/", Order=0)]
        public ArielProject.TaxiServiceAPI.BookRideRequestBody Body;
        
        public BookRideRequest() {
        }
        
        public BookRideRequest(ArielProject.TaxiServiceAPI.BookRideRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BookRideRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string customerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string restaurantName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pickupTime;
        
        public BookRideRequestBody() {
        }
        
        public BookRideRequestBody(string customerName, string restaurantName, string pickupTime) {
            this.customerName = customerName;
            this.restaurantName = restaurantName;
            this.pickupTime = pickupTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookRideResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookRideResponse", Namespace="http://tempuri.org/", Order=0)]
        public ArielProject.TaxiServiceAPI.BookRideResponseBody Body;
        
        public BookRideResponse() {
        }
        
        public BookRideResponse(ArielProject.TaxiServiceAPI.BookRideResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BookRideResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BookRideResult;
        
        public BookRideResponseBody() {
        }
        
        public BookRideResponseBody(string BookRideResult) {
            this.BookRideResult = BookRideResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ArielProject.TaxiServiceAPI.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ArielProject.TaxiServiceAPI.WebService1Soap>, ArielProject.TaxiServiceAPI.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArielProject.TaxiServiceAPI.BookRideResponse ArielProject.TaxiServiceAPI.WebService1Soap.BookRide(ArielProject.TaxiServiceAPI.BookRideRequest request) {
            return base.Channel.BookRide(request);
        }
        
        public string BookRide(string customerName, string restaurantName, string pickupTime) {
            ArielProject.TaxiServiceAPI.BookRideRequest inValue = new ArielProject.TaxiServiceAPI.BookRideRequest();
            inValue.Body = new ArielProject.TaxiServiceAPI.BookRideRequestBody();
            inValue.Body.customerName = customerName;
            inValue.Body.restaurantName = restaurantName;
            inValue.Body.pickupTime = pickupTime;
            ArielProject.TaxiServiceAPI.BookRideResponse retVal = ((ArielProject.TaxiServiceAPI.WebService1Soap)(this)).BookRide(inValue);
            return retVal.Body.BookRideResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArielProject.TaxiServiceAPI.BookRideResponse> ArielProject.TaxiServiceAPI.WebService1Soap.BookRideAsync(ArielProject.TaxiServiceAPI.BookRideRequest request) {
            return base.Channel.BookRideAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArielProject.TaxiServiceAPI.BookRideResponse> BookRideAsync(string customerName, string restaurantName, string pickupTime) {
            ArielProject.TaxiServiceAPI.BookRideRequest inValue = new ArielProject.TaxiServiceAPI.BookRideRequest();
            inValue.Body = new ArielProject.TaxiServiceAPI.BookRideRequestBody();
            inValue.Body.customerName = customerName;
            inValue.Body.restaurantName = restaurantName;
            inValue.Body.pickupTime = pickupTime;
            return ((ArielProject.TaxiServiceAPI.WebService1Soap)(this)).BookRideAsync(inValue);
        }
    }
}
