//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArielProject
{


    public partial class AllRestaurants
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// LblUserName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblUserName;

        /// <summary>
        /// GridView1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView GridView1;

        /// <summary>
        /// PnlEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PnlEmpty;
    }
}
