//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArielProject
{


    public partial class Insert
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// SignUp_FullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox SignUp_FullName;

        /// <summary>
        /// LblNameError - הודעת שגיאה לשדה שם
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblNameError;

        /// <summary>
        /// SignUp_Password control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox SignUp_Password;

        /// <summary>
        /// LblPasswordError - הודעת שגיאה לשדה סיסמה
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblPasswordError;

        /// <summary>
        /// SignUp_Phone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox SignUp_Phone;

        /// <summary>
        /// LblPhoneError - הודעת שגיאה לשדה טלפון
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblPhoneError;

        /// <summary>
        /// DropDownList1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DropDownList1;

        /// <summary>
        /// CheckBoxVegan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox CheckBoxVegan;

        /// <summary>
        /// CheckBoxKosher control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox CheckBoxKosher;

        /// <summary>
        /// CheckBoxVegetarian control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox CheckBoxVegetarian;

        /// <summary>
        /// CheckBoxGluten control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox CheckBoxGluten;

        /// <summary>
        /// CheckBoxPeanuts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox CheckBoxPeanuts;

        /// <summary>
        /// CheckBoxTreeNuts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox CheckBoxTreeNuts;

        /// <summary>
        /// CheckBoxFish control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox CheckBoxFish;

        /// <summary>
        /// CheckBoxSesame control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox CheckBoxSesame;

        /// <summary>
        /// CheckBoxMilk control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox CheckBoxMilk;

        /// <summary>
        /// AddUser control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button AddUser;
    }
}
