//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArielProject
{


    public partial class RestaurantAdmin
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// LblUserName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblUserName;

        /// <summary>
        /// PnlRestaurantTag control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PnlRestaurantTag;

        /// <summary>
        /// LblRestaurantName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblRestaurantName;

        /// <summary>
        /// PnlAdminBadge control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PnlAdminBadge;

        /// <summary>
        /// PnlStats control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PnlStats;

        /// <summary>
        /// PnlAdminMenu control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PnlAdminMenu;

        /// <summary>
        /// LnkAllRestaurants control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink LnkAllRestaurants;

        /// <summary>
        /// LnkUserStats control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink LnkUserStats;

        /// <summary>
        /// BackLink control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink BackLink;

        /// <summary>
        /// LblTotalCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblTotalCount;

        /// <summary>
        /// LblUpcomingCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblUpcomingCount;

        /// <summary>
        /// LblTotalGuests control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblTotalGuests;

        /// <summary>
        /// LblAvgGuests control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblAvgGuests;

        /// <summary>
        /// LblTableTypesChart control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblTableTypesChart;

        /// <summary>
        /// PnlEmptyTable control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PnlEmptyTable;

        /// <summary>
        /// LblTimesChart control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblTimesChart;

        /// <summary>
        /// PnlEmptyTimes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PnlEmptyTimes;

        /// <summary>
        /// LblDaysChart control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblDaysChart;

        /// <summary>
        /// GridView1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView GridView1;

        /// <summary>
        /// PnlEmptyUpcoming control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PnlEmptyUpcoming;
    }
}
