//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArielProject
{


    public partial class RestaurantAdmin
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// LblUserName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblUserName;

        /// <summary>
        /// LblRestaurantName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblRestaurantName;

        /// <summary>
        /// LblTotalCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblTotalCount;

        /// <summary>
        /// LblUpcomingCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblUpcomingCount;

        /// <summary>
        /// LblTotalGuests control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblTotalGuests;

        /// <summary>
        /// LblAvgGuests control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblAvgGuests;

        /// <summary>
        /// RepeaterTableTypes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater RepeaterTableTypes;

        /// <summary>
        /// PnlEmptyTable control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PnlEmptyTable;

        /// <summary>
        /// RepeaterTimes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater RepeaterTimes;

        /// <summary>
        /// PnlEmptyTimes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PnlEmptyTimes;

        /// <summary>
        /// RepeaterDays control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater RepeaterDays;

        /// <summary>
        /// RepeaterUpcoming control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater RepeaterUpcoming;

        /// <summary>
        /// PnlEmptyUpcoming control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PnlEmptyUpcoming;
    }
}
