//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArielProject
{


    public partial class UpdateBookings
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// LblUserName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblUserName;

        /// <summary>
        /// LblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblMessage;

        /// <summary>
        /// PnlList control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PnlList;

        /// <summary>
        /// GridBookings control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView GridBookings;

        /// <summary>
        /// PnlEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PnlEmpty;

        /// <summary>
        /// PnlEdit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel PnlEdit;

        /// <summary>
        /// LblResName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label LblResName;

        /// <summary>
        /// TxtDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TxtDate;

        /// <summary>
        /// CompareValidatorDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CompareValidator CompareValidatorDate;

        /// <summary>
        /// TxtNumGuests control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox TxtNumGuests;

        /// <summary>
        /// BtnCheckAvailability control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnCheckAvailability;

        /// <summary>
        /// GridTimes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView GridTimes;

        /// <summary>
        /// BtnDelete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button BtnDelete;
    }
}
