//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArielProject
{


    public partial class UserStats
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label LblUserName;

        // KPIs
        protected global::System.Web.UI.WebControls.Label LblTotalUsers;
        protected global::System.Web.UI.WebControls.Label LblVegCount;
        protected global::System.Web.UI.WebControls.Label LblKosherCount;
        protected global::System.Web.UI.WebControls.Label LblAllergyCount;
        protected global::System.Web.UI.WebControls.Label LblAdminsCount;

        // Charts (Labels - מקבלים HTML שנבנה בקוד C#)
        protected global::System.Web.UI.WebControls.Label LblAreaChart;
        protected global::System.Web.UI.WebControls.Label LblDietChart;
        protected global::System.Web.UI.WebControls.Label LblAllergyChart;

        // Filters
        protected global::System.Web.UI.WebControls.DropDownList DdlArea;
        protected global::System.Web.UI.WebControls.DropDownList DdlDiet;
        protected global::System.Web.UI.WebControls.DropDownList DdlAllergy;
        protected global::System.Web.UI.WebControls.DropDownList DdlRole;
        protected global::System.Web.UI.WebControls.TextBox TxtName;
        protected global::System.Web.UI.WebControls.Button BtnFilter;
        protected global::System.Web.UI.WebControls.Button BtnClear;

        // Results
        protected global::System.Web.UI.WebControls.Label LblShowing;
        protected global::System.Web.UI.WebControls.Label LblTotal;
        // רשימת המשתמשים המסוננת (Label - מקבל HTML שנבנה בקוד C#)
        protected global::System.Web.UI.WebControls.Label LblUsersList;
        protected global::System.Web.UI.WebControls.Panel PnlEmpty;
    }
}
